apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kexa.fullname" . }}-frontend
  labels:
    {{- include "kexa.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kexa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kexa.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kexa.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
    # --------------------------------------------------------------------------------------------- #
        # kexafrontend
        - name: kexa-enterprise-front
          image: kexa/kexa-enterprise-front
          {{- if (merge .Values.kexafront.environment .Values.kexafront.environment) }}
          env:
          {{- range $name, $value := merge .Values.kexafront.environment .Values.kexafront.environment }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: 9000
