apiVersion: v1
kind: Secret
metadata:
  name: kexa-pull-secret
type: Opaque
data:
  docker-server: https://registry-1.docker.io/v2/
  docker-username: kexa
  docker-password: dckr_oat_R0vhUVTwQ13ozEsEsSEv8m6mzAtodo43