apiVersion: v1
kind: Secret
metadata:
  name: kexa-pull-secret
type: Opaque
data:
  docker-server: ${{.Values.secretpull.docker-server}}
  docker-username: ${{.Values.secretpull.docker-username}}
  docker-password: ${{.Values.secretpull.docker-password}}
