name: versioning

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:

  ci:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Prep plugins
        run: |
          npm install -D @semantic-release/changelog @semantic-release/git
      - name: Run semantic release
        id: ver
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest release of Kexa interface
        uses: rez0n/actions-github-release@794c12f5e8d629e6ca329cf2e2daeb0f0ce6a3ce # main
        id: get_latest_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "4urcloud/kexa-enterprise"
          type: "stable"
      - name: print new latest version
        run: echo ${{ steps.get_latest_release.outputs.release }}


      - name: Login to Docker Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_NAME}}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Push on Docker Registry
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
        with:
          context: ./
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_NAME}}/kexa/kexa-enterprise:${{ steps.get_latest_release.outputs.release }}
            ${{ secrets.DOCKER_REGISTRY_NAME}}/kexa/kexa-enterprise:latest